// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    // Supabase의 direct connection(포트 5432)을 사용합니다.
    // pgbouncer로 풀링된 DATABASE_URL은 DDL(migrate)에 적합하지 않습니다.
    url: process.env["DIRECT_URL"],
  },
});
